version: 2.0

orbs:
  node: circleci/node@4.0.0

jobs:
  setup:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - node/install-yarn
      - run: node --version
      - run: yarn --version
      - node/install-packages:
        pkg-manager: yarn
      - persist_to_workspace:
        root: .
  lint:
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - attach_workspace:
        at: .
      - run: yarn lint

workflows:
  ci:
    jobs:
      - setup
      - lint:
        requires:
          - setup
